# Generated by Django 3.1.2 on 2020-11-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='یک نام منحصر به فرد که از نام محصول ساخته شده', max_length=255, unique=True),
        ),
    ]
