# Generated by Django 3.1.2 on 2020-11-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20201110_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='یک نام منحصر به فرد که از نام محصول ساخته شده.'),
        ),
    ]
