# Generated by Django 3.1.2 on 2020-11-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20201110_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='نام_محصول',
        ),
    ]
