# Generated by Django 3.1.2 on 2020-11-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20201110_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='نام_محصول',
            new_name='name',
        ),
    ]
