# Generated by Django 3.1.2 on 2020-12-29 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('ANG', 'انگور'), ('BRN', 'برنج'), ('GOJ', 'گوجه'), ('KHI', 'خیار')], help_text='نام گیاه', max_length=150)),
                ('slug', models.SlugField(help_text='نامی منحصر به فر انتخاب کنید', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField()),
                ('Age_Stirng', models.CharField(blank=True, help_text='سن گیاه', max_length=4)),
                ('Age_Numberic', models.IntegerField(help_text='اگر سن گیاه به صورت عددی باشد.')),
                ('Weather', models.CharField(choices=[('KOH', 'کوهستانی'), ('MOT', 'معتدل'), ('GKH', 'گرم و خشک'), ('GMA', 'گرم و مرطوب')], default='MOT', help_text='شرایط آب و هوایی منطقه کاربر.', max_length=3)),
                ('Water', models.CharField(choices=[('DEM', 'دیم'), ('ABI', 'آبی')], default='DEM', help_text='شرایط آبیاری گیاه', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Area', models.FloatField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formola.category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='formola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOS', 'فسفر'), ('NIT', 'نیتروژن'), ('FEA', 'آهن'), ('NAC', 'سدیم')], help_text='نام کود', max_length=3)),
                ('_water', models.IntegerField(help_text='مقدار در آب')),
                ('_Vahed', models.CharField(choices=[('GER', 'گرم'), ('MIL', 'میلی گرم'), ('KIL', 'کیلو گرم'), ('PEY', 'پیمانه')], max_length=3)),
                ('meghdar', models.IntegerField(help_text='مقدار کود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realte', models.ManyToManyField(to='formola.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
