# Generated by Django 3.1.2 on 2020-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='Planet_type',
            field=models.CharField(choices=[('ZER', 'زراعی'), ('BAG', 'باغی'), ('GOL', 'گلخانه ای')], default='GOL', max_length=3),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Age_Stirng',
            field=models.IntegerField(blank=True, help_text='سن گیاه'),
        ),
    ]
