# Generated by Django 3.1.2 on 2020-12-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0002_auto_20201229_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formola',
            name='_Vahed',
            field=models.CharField(choices=[('GER', 'گرم'), ('MIL', 'میلی گرم'), ('KIL', 'کیلو گرم'), ('PEY', 'پیمانه')], default='GER', max_length=3),
        ),
    ]
