# Generated by Django 3.1.2 on 2020-12-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0003_auto_20201229_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='Age_Stirng',
        ),
    ]
