# Generated by Django 3.1.2 on 2020-12-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0004_remove_farmer_age_stirng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formola',
            old_name='realte',
            new_name='relate',
        ),
    ]
