# Generated by Django 3.1.2 on 2020-12-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0005_auto_20201229_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formola',
            name='relate',
        ),
    ]
