# Generated by Django 3.1.2 on 2020-12-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0007_auto_20201229_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
