# Generated by Django 3.1.2 on 2021-01-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formola', '0009_auto_20210104_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formola',
            name='name',
            field=models.CharField(choices=[('KG', 'خیار گلخانه'), ('KM', 'خیار مذرعه'), ('KH', 'خیار هیدروپونیک'), ('FM', 'فلفل دلمه مزرعه'), ('FH', 'فلفل دلمه هیدرو پونیک'), ('GM', 'گوجه فرنگی مذرعه'), ('GH', 'گوجه فرنگی هیدروپونیک ')], default='KG', max_length=2),
        ),
        migrations.CreateModel(
            name='userinput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roshd_date', models.CharField(choices=[('KB', 'کشت بهاره'), ('KP', 'کشت پاییزه'), ('GK', 'قبل کشت'), ('RR', 'رشد رویشی'), ('GD', 'گلدهی و تشکیل میوه'), ('AM', 'مرحله رشدي گیاهچه تا تشکیل اولین میوه'), ('EB', 'مرحله رشدي تشکیل میوه تا اتمام برداشت '), ('DH', 'دو هفته اول'), ('RY', 'رشد رویشی'), ('GM', 'گلدهی تا تشکیل اولین میوه'), ('TB', 'تشکیل میوه تا اولین برداشت'), ('NT', 'نشا تا ظهور اولین گل'), ('BG', 'بعد از گلدهی'), ('PA', 'پس از کاشت'), ('RM', 'رشد میوه'), ('CA', 'چین اول'), ('CD', 'چین دوم'), ('CS', 'چین سوم'), ('AB', 'آخرین برداشت')], default='KB', max_length=2)),
                ('name', models.CharField(choices=[('KG', 'خیار گلخانه'), ('KM', 'خیار مذرعه'), ('KH', 'خیار هیدروپونیک'), ('FM', 'فلفل دلمه مزرعه'), ('FH', 'فلفل دلمه هیدرو پونیک'), ('GM', 'گوجه فرنگی مذرعه'), ('GH', 'گوجه فرنگی هیدروپونیک ')], default='KG', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
