# Generated by Django 3.1.2 on 2021-01-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0012_auto_20210110_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='formola',
            name='nitrat_maniaziom',
            field=models.CharField(blank=True, help_text='نیترات منیزیم', max_length=100, null=True),
        ),
    ]
