# Generated by Django 3.1.2 on 2021-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formola', '0013_formola_nitrat_maniaziom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formola',
            name='content',
            field=models.CharField(default='توضیحات اضافه:', help_text='توضیحات اضافه', max_length=1000),
        ),
    ]
