# Generated by Django 3.1.2 on 2020-12-18 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('BAQ', 'باغی'), ('ZER', 'زراعی'), ('GOL', 'گلخانه ای')], default='GOLKHANE', max_length=3)),
                ('Name', models.CharField(help_text='نام گیاه', max_length=150)),
                ('Age_Stirng', models.CharField(blank=True, help_text='اگر سن گیاه به صورت بخش بندی باشد', max_length=4)),
                ('Weather', models.CharField(choices=[('KOH', 'کوهستانی'), ('MOT', 'معتدل'), ('GKH', 'گرم و خشک'), ('GMA', 'گرم و مرطوب')], default='MOT', help_text='شرایط آب و هوایی منطقه کاربر.', max_length=3)),
                ('Water', models.CharField(choices=[('DEM', 'دیم'), ('ABI', 'آبی')], default='DEM', help_text='شرایط آبیاری گیاه', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Area', models.FloatField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'اطلاعات گیاه',
                'ordering': ['-created_at'],
            },
        ),
    ]
